FROM node:18-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app/src/frontend

COPY src/frontend /app

RUN npm install -g corepack@latest
RUN corepack enable
RUN pnpm i


EXPOSE 3000

CMD pnpm dev
